const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const source=name=>fs.readFileSync(path.join(__dirname,'../frontend',name),'utf8');
function client(){let calls=0;const window={location:new URL('https://task.test/index.html?demo=1')};const context=vm.createContext({window,document:{addEventListener(){}},URL,URLSearchParams,Headers,Response,crypto:webcrypto,fetch:async()=>{calls++;throw new Error('No real requests');}});vm.runInContext(source('demo.js'),context);vm.runInContext(source('auth-client.js'),context);const request=(p,m='GET',body)=>window.TaskAuth.request(p,{method:m,...(body?{body:JSON.stringify(body)}:{})});return{request,json:async p=>(await request(p)).json(),change:async action=>request('/api/teams/1/billing/'+action,'POST'),calls:()=>calls};}
test('demo has explicit simulation and owner-inclusive free limit',async()=>{const c=client(),state=await c.json('/api/teams/1/billing');assert.equal(state.simulation,true);assert.equal(state.monthlyYen,500);assert.equal(state.memberLimit,3);assert.equal(state.memberCount,2);assert.equal((await c.change('demo-member')).status,200);assert.equal((await c.change('demo-member')).status,409);assert.equal(c.calls(),0);});
test('Pro simulation unlocks every owned team and never changes XP',async()=>{const c=client(),xp=(await c.json('/api/pet')).totalExperience;const other=await(await c.request('/api/teams','POST',{name:'Other'})).json();await c.change('checkout');for(let i=0;i<5;i++)assert.equal((await c.change('demo-member')).status,200);assert.equal((await c.json('/api/teams/1/billing')).memberLimit,null);assert.equal((await c.json(`/api/teams/${other.team.id}/billing`)).memberLimit,null);assert.equal((await c.json('/api/pet')).totalExperience,xp);assert.equal(c.calls(),0);});
test('cancel and renewal failure preserve members and stop only new joins',async()=>{const c=client();await c.change('checkout');await c.change('demo-member');await c.change('demo-member');await c.change('cancel');assert.equal((await c.json('/api/teams/1/billing')).plan,'pro');await c.change('demo-fail');assert.equal((await c.change('demo-member')).status,409);assert.equal((await c.json('/api/teams/1/billing')).memberCount,4);await c.change('end_now');assert.equal((await c.json('/api/teams/1/billing')).hasContract,false);assert.equal((await c.json('/api/teams/1/tasks')).totalCount,3);});
test('account contract survives deleting its last team and can still be managed',async()=>{const c=client();await c.change('checkout');assert.equal((await c.request('/api/teams/1','DELETE')).status,204);assert.equal((await c.json('/api/user/billing')).plan,'pro');assert.equal((await c.json('/api/user/billing')).ownedTeamCount,0);await c.request('/api/user/billing/end_now','POST');assert.equal((await c.json('/api/user/billing')).hasContract,false);assert.equal(c.calls(),0);});
test('billing UI uses text nodes and guarded redirect without card capture',()=>{const js=source('team-billing.js');assert.doesNotMatch(js,/innerHTML|insertAdjacentHTML|localStorage|sessionStorage|sk_live_|sk_test_/);assert.match(js,/checkout\.stripe\.com/);assert.match(js,/simulation/);assert.match(js,/generation/);assert.match(source('index.html'),/team-billing-panel/);});
test('purchase view is inside the existing team dialog and does not add a main board panel',()=>{const html=source('index.html');assert.match(html,/<section id="billing-flow"[^>]+hidden/);assert.ok(html.indexOf('id="billing-flow"')>html.indexOf('id="team-modal"'));assert.ok(html.indexOf('id="billing-flow"')<html.indexOf('id="team-mode-tabs"'));assert.match(source('team-billing.css'),/billing-flow-open/);});
test('closing the team dialog and switching workspace invalidate pending billing views',()=>{const js=source('options.js');assert.match(js,/if \(modal === teamModal\).*TeamBilling\.reset\(\)/);assert.match(js,/async function switchWorkspace\(teamId\) \{\s+if \(typeof TeamBilling[^\n]+TeamBilling\.reset\(\)/);});
